spark.sql.catalog.mycatalog=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.mycatalog.catalog-impl=org.apache.iceberg.hadoop.HadoopCatalog
spark.sql.catalog.mycatalog.warehouse=s3a://iceberg/warehouse

spark.hadoop.fs.s3a.access.key=minio
spark.hadoop.fs.s3a.secret.key=minio123
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.path.style.access=true
